name: Deploy Django App

on:
  push:
    branches:
      - testing

jobs:
  test-unitario:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u test_user --password=test_password"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.1

      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt

      - name: Run migrations
        env:
          DATABASE_URL: mysql://test_user:test_password@127.0.0.1:3306/test_db
        run: |
          source env/bin/activate
          python manage.py migrate

      - name: Run Django tests
        env:
          DATABASE_URL: mysql://test_user:test_password@127.0.0.1:3306/test_db
        run: |
          source env/bin/activate
          python manage.py test

      - name: Start Django Server
        env:
          DATABASE_URL: mysql://test_user:test_password@127.0.0.1:3306/test_db
        run: |
          source env/bin/activate
          python manage.py runserver 0.0.0.0:8000 &  # Levanta Django en segundo plano
          sleep 5  # Espera unos segundos para que arranque

  test-e2e:
    needs: test-unitario
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: 
          npm install
          npx create-codeceptjs .  
          npx codeceptjs init
          npx playwright install 

      - name: Run E2E tests
        run: |
          npx codeceptjs run --steps

      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-screenshots
          path: output/

  docker:
    needs: test-e2e
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/django-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/django-app:latest

      - name: Run container
        run: |
          docker run -d -p 8000:8000 \
            -e DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
            -e DATABASE_USER=${{ secrets.DATABASE_USER }} \
            -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
            -e DATABASE_HOST=${{ secrets.DATABASE_HOST }} \
            -e DATABASE_PORT=${{ secrets.DATABASE_PORT }} \
            --name django_app ${{ secrets.DOCKER_USERNAME }}/django-app:latest


      