name: Deploy Django App

on:
  push:
    branches:
      - main  # O la rama que uses para producción

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/django-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/django-app:latest

      - name: Run container
        run: |
          docker run -d -p 8000:8000 \
            -e DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
            -e DATABASE_USER=${{ secrets.DATABASE_USER }} \
            -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
            -e DATABASE_HOST=${{ secrets.DATABASE_HOST }} \
            -e DATABASE_PORT=${{ secrets.DATABASE_PORT }} \
            --name django_app ${{ secrets.DOCKERHUB_USERNAME }}/django-app:latest
