name: Run Django Tests

on:
  push:
    branches:
      - testing
  pull_request:
    branches:
      - testing

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Instalar ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '[0-9]+(\.[0-9]+)+')
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget -N "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Ejecutar tests
        run: |
          python manage.py test
