name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python y dependencias
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Correr tests de Django
        run: |
          python manage.py test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir y subir la imagen a DockerHub
        run: |
          docker build -t martinlescano/miapp:latest .
          docker push martinlescano/miapp:latest

  test-e2e:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias de CodeceptJS
        run: |
          npm install -g codeceptjs
      
      - name: Ejecutar pruebas E2E
        run: |
          npx codeceptjs run --steps --override '{ 
            "helpers": { 
              "Puppeteer": { 
                "chrome": { "executablePath": "/usr/bin/google-chrome-stable" }, 
                "args": ["--no-sandbox", "--disable-setuid-sandbox"]
              } 
            } 
          }'
        